version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
init:
- cmd: git config --global core.autocrlf true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  parallel: true
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: BE2IOH0bTyc3Dpm1Jazaj4lB/LOiW5J9czpUD7D32WEqZ7Rxo4nUyYE8Zana6Dhv
  on:
    appveyor_repo_tag: true