version: 1.2.0-ci.{build}
image: Visual Studio 2019
configuration: Release
init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
    }
    else
    {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_BUILD_VERSION)+sha.$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
    }
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
cache: 
  - '%USERPROFILE%\.nuget\packages'
before_build:
- cmd: nuget restore -Verbosity quiet
build:
  publish_nuget: true
  parallel: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 2oHOy0Al+2Fomg3fePwi7WoZid4nOTjwF1+2d8sfCdKgK862wmHZ2dqQX3Vr3azh
  on:
    appveyor_repo_tag: true
